### ISSUE TITLE
читай описание мне лень всё впихивать в заголовок

### ISSUE THREAD

**Issue by Nerwind** [cafeed28/zerocore#15]
короче в комментах под уровнями все отображаются как админы ну тоесть есть приписка Administrator под комментарием блять короче скрин кину
![image](https://user-images.githubusercontent.com/71249370/116642151-9f1ba400-a987-11eb-81b9-c5480a3e7cd6.png)
![image](https://user-images.githubusercontent.com/71249370/116642161-a2af2b00-a987-11eb-992b-67a0bcf66d92.png)

**Comment by cafeed28** [comment]
пофикшено в 1.1.7-beta
