### ISSUE TITLE
не отображаются выложенные тобой анлистед уровни в май онлайн левелс

### ISSUE THREAD

**Issue by Nerwind** [cafeed28/zerocore#18]
в титле всё написал так что вот тебе рецепт фасоли:
Фасоль перебрать, помыть, замочить в холодной воде на 2-6 часов.
Налить в казанок 1 л воды. Вскипятить. Затем положить в кипящую воду фасоль и варить до готовности на небольшом огне (около часа), охладить.
Чеснок очистить, мелко порубить.
Зелень промыть, мелко нарезать.
Разогреть сковороду, налить растительное масло. Выложить томатную пасту. Томат-пасту спассеровать на растительном масле (около 2-3 минут).
Заправить лобио с томатом солью, специями для плова, рубленым чесноком, кинзой.
Проварить лобио в томатном соусе 2-3 минуты на небольшом огне.
готово

**Comment by discographi** [comment]
нихуя не понял но за рецепт фасоли спс

**Comment by cafeed28** [comment]
починил уже хуй знает когда, отображаются, рецепт классный
