### ISSUE TITLE
иногда запросы не поступают

### ISSUE THREAD

**Issue by discographi** [cafeed28/zerocore#19]
всё в титле вот рецепт пельменного теста:

-------------------
<div class="article-text">
  <p>Как ни странно, но найти хороший рецепт пельменного теста не так уж
 и просто, хотя его состав и правильные пропорции просчитаны уже давным 
давно. Хорошее пельменное тесто должно быть не только вкусным, но и 
обладать определенными характеристиками. Оно не должно разбухать при 
варке, должно хорошо и тонко раскатываться, должно хорошо поддаваться 
лепке и в готовом виде должно быть мягким и приятным. Хочу поделиться 
самым лучшим на мой (и не только) взгляд рецептом теста для пельменей и 
вареников, которое полностью удовлетворяет всем этим требованиям.</p>
</div>

<div class="article-breadcrumbs">
  <p>
    Категория:
          <span>
        <a href="https://www.povarenok.ru/recipes/category/25/">
          Выпечка
        </a>
      </span>
              <span>
        <a href="https://www.povarenok.ru/recipes/category/26/">
          Тесто
        </a>
      </span>
              <span>
        <a href="https://www.povarenok.ru/recipes/category/184/">
          Пресное тесто
        </a>
      </span>
      </p>
      <p>
      Кухня:
      <span>
        <a href="https://www.povarenok.ru/recipes/kitchen/101/">Русская</a>
      </span>
    </p>
  </div>

<h2>Ингредиенты для «Правильное тесто для вареников и пельменей»:</h2>
<div class="ingredients-bl">
            
      <ul>
                  <li>
                          <span itemprop="ingredient" itemscope="" itemtype="http://data-vocabulary.org/RecipeIngredient">
            
                                          <a href="https://www.povarenok.ru/recipes/ingredient/2339/">
                  <span itemprop="name">Мука пшеничная</span>
                </a>
                /
                <a href="https://www.povarenok.ru/recipes/ingredient/1156/">
                  <span itemprop="name">Мука</span>
                </a>
                          
            (зависит от сорта муки и от ее влажности, стакан = 225 мл)
                          —
              <span itemprop="amount">2-3 стак.</span>
                        </span>          </li>
                  <li>
                          <span itemprop="ingredient" itemscope="" itemtype="http://data-vocabulary.org/RecipeIngredient">
            
                                          <a href="https://www.povarenok.ru/recipes/ingredient/1125/">
                  <span itemprop="name">Молоко</span>
                </a>
                          
            (стакан = 225 мл)
                          —
              <span itemprop="amount">1/2 стак.</span>
                        </span>          </li>
                  <li>
                          <span itemprop="ingredient" itemscope="" itemtype="http://data-vocabulary.org/RecipeIngredient">
            
                                          <a href="https://www.povarenok.ru/recipes/ingredient/351/">
                  <span itemprop="name">Вода</span>
                </a>
                          
            (стакан = 225 мл)
                          —
              <span itemprop="amount">1/3 стак.</span>
                        </span>          </li>
                  <li>
                          <span itemprop="ingredient" itemscope="" itemtype="http://data-vocabulary.org/RecipeIngredient">
            
                                          <a href="https://www.povarenok.ru/recipes/ingredient/3562/">
                  <span itemprop="name">Яйцо куриное</span>
                </a>
                          
            
                          —
              <span itemprop="amount">1 шт</span>
                        </span>          </li>
                  <li>
                          <span itemprop="ingredient" itemscope="" itemtype="http://data-vocabulary.org/RecipeIngredient">
            
                                          <a href="https://www.povarenok.ru/recipes/ingredient/1067/">
                  <span itemprop="name">Масло растительное</span>
                </a>
                          
            
                          —
              <span itemprop="amount">1 ч. л.</span>
                        </span>          </li>
                  <li>
                          <span itemprop="ingredient" itemscope="" itemtype="http://data-vocabulary.org/RecipeIngredient">
            
                                          <a href="https://www.povarenok.ru/recipes/ingredient/1681/">
                  <span itemprop="name">Соль</span>
                </a>
                          
            
                          —
              <span itemprop="amount">1 ч. л.</span>
                        </span>          </li>
              </ul>
      
      <p><strong>Время приготовления:</strong> <time datetime="PT15M" itemprop="totalTime">15 минут</time></p>
    </div>

  <div id="nae-value-bl" data-rid="23856">
                <h2>Пищевая и энергетическая ценность:</h2>
      

Готового блюда
--
ккал                                           1276.1 ккал | белки                                           44 г | жиры                                           11.6 г | углеводы                                           252.4 г
100 г блюда
ккал143.4 ккал | белки4.9 г | жиры1.3 г | углеводы28.4 г

</center>

<h2>Рецепт «Правильное тесто для вареников и пельменей»:</h2>

      <div class="cooking-bl" itemprop="recipeInstructions">
              <span class="cook-img">
          <a rel="facebox" target="_blank" href="https://www.povarenok.ru/data/cache/2013may/10/19/289749_40763-640x480.jpg">
            <img alt="" title="" src="https://www.povarenok.ru/data/cache/2013may/10/19/289749_40763-300x0.jpg">
          </a>
        </span>
        
      
      <div>
        <p>Классическое пельменное тесто должно состоять из муки, яиц и 
воды (молока)- этот состав определился многовековым опытом многих 
народов. Другой вопрос стоит в определении правильных пропорций и тут 
опять на помощь приходит опыт. Идеальное соотношение яиц и воды - на 
каждое среднее яйцо необходимо брать 2 стакана муки. Для получения 
необходимой вязкости теста добавляется тёплая вода и/или молоко. 
Растительное масло делает тесто более нежным и податливым. Соль 
добавляется по вкусу.<br>
Итак, высыпаем на стол или в чашку 2 стакана муки. В центре полученной 
горки делаем небольшое углубление, разбиваем туда яйцо и добавляем 
тёплую воду, смешанную с молоком и солью.</p>
      </div>
    </div>
      <div class="cooking-bl" itemprop="recipeInstructions">
              <span class="cook-img">
          <a rel="facebox" target="_blank" href="https://www.povarenok.ru/data/cache/2013may/07/19/289750_69672-640x480.jpg">
            <img alt="" title="" src="https://www.povarenok.ru/data/cache/2013may/07/19/289750_69672-300x0.jpg">
          </a>
        </span>
        
      
      <div>
        <p>Тщательно вымешиваем тесто, добавляем в него 1 чайную ложку масла и ещё раз хорошенько вымешиваем.</p>
      </div>
    </div>
      <div class="cooking-bl" itemprop="recipeInstructions">
              <span class="cook-img">
          <a rel="facebox" target="_blank" href="https://www.povarenok.ru/data/cache/2013may/09/19/289751_29143-640x480.jpg">
            <img alt="" title="" src="https://www.povarenok.ru/data/cache/2013may/09/19/289751_29143-300x0.jpg">
          </a>
        </span>
        
      
      <div>
        <p>Полученное тесто накрываем тканью или полотенцем и оставляем 
на 40 минут для созревания. Через 40 минут наше замечательное тесто 
будет готово.</p>
      </div>
    </div>
      <div class="cooking-bl" itemprop="recipeInstructions">
              <span class="cook-img">
          <a rel="facebox" target="_blank" href="https://www.povarenok.ru/data/cache/2013apr/21/19/289752_59656-640x480.jpg">
            <img alt="" title="" src="https://www.povarenok.ru/data/cache/2013apr/21/19/289752_59656-300x0.jpg">
          </a>
        </span>
        
      
      <div>
        <p>Как видите, всё очень и очень просто!<br>
Будьте счастливы и здоровы!<br>
Приятного аппетита!</p>
      </div>
    </div>
  

<div>Этот рецепт - участник акции <strong class="bb">"Готовим вместе - кулинарная неделя"</strong>.</div>

**Comment by cafeed28** [comment]
чини рецепт

**Comment by discographi** [comment]
иди нахуй

**Comment by cafeed28** [comment]
ладно тогда рецепт мяса для пельменей

**Comment by discographi** [comment]
Мясо для пельменей Мясо для пельменей 1 0 Приготовил : Ольга Макарова 06.10.2016 Время приготовления: 15 мин Сохранить Я приготовил(а) Оценить Распечатать Если вам предстоит лепить пельмени, то значит возникнет необходимость в приготовлении вкусного фарша. А это половина успеха, так что воспользуйтесь этим простым, полезным рецептом мяса для пельменей. Описание приготовления: Для приготовления пельменей очень важно правильно подготовить фарш. Для него лучше всего использовать несколько видов мяса. Традиционно – это свинина и говядина. Но возможны различные варианты. В любом случае в фарше должно быть достаточно большое количество лука, который придаст особенную сочность. Так, что когда возникает вопрос, как приготовить мясо для пельменей, прежде всего, следует выбирать постные и более жирные куски. Но увлекаться более жирным мясом не стоит. Назначение: На обед / На ужин Основной ингредиент: Мясо / Овощи / Говядина / Свинина / Лук Блюдо: Начинки География кухни: Русская кухня Ингредиенты: Говядина — 300 Грамм Свинина — 300 Грамм Лук репчатый — 1 Штука Вода — 100 Миллилитров Сахар — 1 Грамм Соль — 1 Ст. ложка Перец — 0,5 Грамма Количество порций: 1 Как приготовить "Мясо для пельменей" Мясо для пельменей - фото шаг 1 1. Выберите мясо для фарша. Для этого возьмите мякоть говядины и свинины. Затем мясо тщательно помойте. Срежьте пленки (обычно их много на говядине). Нарежьте мясо на куски, которые удобно пропускать через мясорубку. Лук очистите от шелухи. Разрежьте луковицу на несколько кусков. Измельчите свинину и говядину вместе с луком, прокрутив через мясорубку. Мясо для пельменей - фото шаг 2 2. В перекрученное с луком мясо добавьте немного холодной воды. Посолите. По вкусу поперчите. Хорошенько перемешайте. Мясо для пельменей - фото шаг 3 3. Фарш тщательно вымесите. Затем его отбейте, используя для этого дно глубокой миски или разделочную доску. После этого фарш будет готов к лепке пельменей. Подробнее: https://povar.ru/recipes/myaso_dlya_pelmenei-46267.html

**Comment by cafeed28** [comment]
пойду пельменей сделаю потом починю

**Comment by discographi** [comment]
кафiф приготовил пельмени.

**Comment by discographi** [comment]
блять а нахуя я иссуе закрыл

**Comment by cafeed28** [comment]
как я понял, это не проблемы с сервером, а проблема с клиентом
