### ISSUE TITLE
в меню не играет новый мерин

### ISSUE THREAD

**Issue by cafeed28** [cafeed28/zerocore#2]
уровень: критичный

**Comment by pisyaSlona** [comment]
согласен, ждём когда разработчики исправят...

**Comment by cafeed28** [comment]
скоро выкачу фикс

**Comment by pisyaSlona** [comment]
ГДЕ **_ФИКС_** БЛЯТЬ ТРИ ДНЯ прошло нахуй

**Comment by cafeed28** [comment]
баг дохуя сложный

**Comment by pisyaSlona** [comment]
> баг дохуя сложный

ДА ПОХУЙ ГДЕ ФИКС НАХУЙ ШПТЛ АЬОЗТПЧВЫАМСЩУ КЕЩПЕЫПШЩГАСВКАБДЛОВПЧЫАМИМИШШГВПШГ7ВАШГ

**Comment by cafeed28** [comment]
кароче фiкса не будет это фатальная ошибка архитектуры x86
