### ISSUE TITLE
Коменты под лвлами стоят в обратном порядке.

### ISSUE THREAD

**Issue by bettercalldelta** [cafeed28/zerocore#22]
А спонсор данной исуе: RAID SHADOW LEGENDS!!!

RAID SHADOW LEGENDS ЭТО ИНТЕРЕСНАЯ ОНЛАЙН ИГРА ДЛЯ ВАШЕГО СМАРТФОНА ТЫСЯЧИ РАЗЛИЧНЫХ РЕЖИМОВ ГЕРОЕВ И ЭВЕНТОВ ЖДУТ ВАС УЖЕ СЕГОДНЯ АБСОЛЮТНО БЕСПЛАТНО А СИСТЕМА КЛАНОВЫХ БИТВ НИКОГДА НЕ ДАСТ ВАМ ЗАСКУЧАТЬ ПРОКАЧИВАЙ СВОЕГО ПЕРСОНАЖА И ПОЛУЧАЙ КРУТЫЕ БОНУСЫ ПО ССЫЛКЕ В ОПИСАНИИ УЖЕ СЕЙЧАС А ПО ПРОМОКОДУ КРИПЕР2004 ТЫ ПОЛУЧИШЬ БЕСПЛАТНОГО ГЕРОЯ 100 ТЫСЯЧ МОНЕТ 50 РУБИНОВ ТРИ ОГНЕННЫХ МЕЧА СМЕРТИ ДВЕ ЭССЕНЦИИ ДУШИ ТЁМНОГО ДРАКОНА ДВЕНАДЦАТЬ СУНДУКОВ БЕСКОНЕЧНОГО ОТЧАЯНИЯ ТРИ ОСКОЛКА СЕВЕРНОГО ГОЛЕМА ОДНО ЯДРО АБСОЛЮТНОГО УЛУЧШЕНИЯ 200 ТОКЕНОВ МАГИЧЕСКОГО ЗАЧАРОВАНИЯ 10 КРИСТАЛЛОВ МОМЕНТАЛЬНОГО ВОСКРЕШЕНИЯ А ТАКЖЕ ЗЕЛЬЕ УСКОРЕНИЯ ЗЕЛЬЕ ЛЕЧЕНИЯ ЗЕЛЬЕ ОБУЧЕНИЯ ЗЕЛЬЕ УВЕЛИЧЕНИЯ И ВСЁ ЭТО АБСОЛЮТНО БЕСПЛАТНО КАЧАЙ ИГРУ ПРЯМО СЕЙЧАС ПО ССЫЛКЕ В ОПИСАНИИ ВВОДИ МОЙ ПРОМОКОД И ПОГРУЖАЙСЯ В ОПАСНЫЙ МИР БЕСКОНЕЧНЫХ СРАЖЕНИЙ ГИЛЬДИЙ И ВЕСЕЛЬЯ

**Comment by bettercalldelta** [comment]
где актив

**Comment by cafeed28** [comment]
вроде тоже пофикшено уже
