### ISSUE TITLE
умер

### ISSUE THREAD

**Issue by Partur1** [cafeed28/zerocore#5]
хотел потестить все (эедпоинты) а там нету темной теми

**Comment by cafeed28** [comment]
а де нет тёмной теми

**Comment by Partur1** [comment]
я когда к эндпоинтам запросы отправляю 
там белое все
и на белом
черным текстом ответ

**Comment by cafeed28** [comment]
пот ому что

**Comment by Partur1** [comment]
- [ ] Сделай темную тему в эндпоинтах

- [ ] Сделай шашборд

**Comment by pisyaSlona** [comment]
у меня письки нету

**Comment by pisyaSlona** [comment]
ой

**Comment by pisyaSlona** [comment]
не туда

**Comment by cafeed28** [comment]
ебать чат))00)

**Comment by pisyaSlona** [comment]
партур оцени https://github.com/cafeed28/zerocore/issues/6

**Comment by cafeed28** [comment]
как закрыть нахуй

**Comment by pisyaSlona** [comment]
твоей пиздой
