### ISSUE TITLE
BUG: у меня мать сгорела

### ISSUE THREAD

**Issue by pisyaSlona** [cafeed28/zerocore#6]
### **_У меня мать сгорела. Пошли в клинику на обследование. И ничего не нашли. У меня так слюни изо рта и капали. Сейчас еще приходит. Да ты не бойся. Сейчас есть много похожих на тебя. Вылупились. А кто вылупились, вы спросите? Что им у меня в голове ответят? А вылупился нервинд. Откуда все это знаю. Почему в моей голове все это началось? Где я выросла? Скажите. Вы где родились? Где раньше жили? Ну? Дальше? Кто вы теперь? Кто вы? Я вас видела в церкви. А сегодня? Я кто нахуй? Я вот сейчас на огороде возьму тяпку и пойду картошку окучивать. Что я вам сказала? Вы тоже меня видите? Вы тоже меня видите? Не поняла. Может, вы тогда скажете, кто я? Я незнаю кто ты. Вот и блять незнаю! Вы сначала туда поднимитесь, а потом мы увидимся. И тогда я обязательно вам скажу. А теперь идите нахуй и не смейте меня искать. Блять незнаю, кто я! Не блять кто! Прошли мимо и все. Вот просто прошли нахуй, и всё! Не надо ходить. Надо потом. А то я еще хуже буду, чем вы. Идите нахуй нахуй, куда шли. Идите нахуй нахуй. Прошли, нахуй нахуй. Да я же говорю, вы не слушаете!_**

**Comment by cafeed28** [comment]
ух ебаный рот

**Comment by pisyaSlona** [comment]
баг пофиксил?

**Comment by cafeed28** [comment]
да

**Comment by pisyaSlona** [comment]
> да

пизда
